-- =========================================================
-- Schema: ZAKATDB
-- Oracle XE 18c+
-- Auto-increment via IDENTITY (NO sequences, NO triggers)
-- =========================================================

-- Optional: create user if needed (comment out if user exists)
-- CREATE USER zakatdb IDENTIFIED BY zakat123;
-- GRANT CONNECT, RESOURCE TO zakatdb;
-- ALTER USER zakatdb QUOTA UNLIMITED ON USERS;

ALTER SESSION SET CURRENT_SCHEMA = ZAKATDB;

-- =========================================================
-- ADMIN
-- =========================================================
CREATE TABLE ADMIN (
    ADMINID NUMBER GENERATED ALWAYS AS IDENTITY,
    USERNAME VARCHAR2(255),
    PASSWORD VARCHAR2(255),
    PHONENUM VARCHAR2(15),
    CONSTRAINT PK_ADMIN PRIMARY KEY (ADMINID)
);

-- =========================================================
-- STUDENT
-- =========================================================
CREATE TABLE STUDENT (
    STUDENTID NUMBER GENERATED ALWAYS AS IDENTITY,
    PASSWORD VARCHAR2(255),
    MATRICNO VARCHAR2(50),
    NAME VARCHAR2(255),
    INCOME NUMBER(10,2),
    COURSECODE VARCHAR2(50),
    COURSENAME VARCHAR2(255),
    CAMPUS VARCHAR2(255),
    EMAIL VARCHAR2(255),
    PHONENUM VARCHAR2(15),
    ADDRESS VARCHAR2(255),
    CONSTRAINT PK_STUDENT PRIMARY KEY (STUDENTID)
);

-- =========================
-- FAMILY (FIXED + VERIFIED)
-- =========================
CREATE TABLE FAMILY (
    FAMILYID NUMBER GENERATED ALWAYS AS IDENTITY,
    STUDENTID NUMBER NOT NULL,
    NAME VARCHAR2(255),
    RELATIONSHIP VARCHAR2(50),
    AGE NUMBER,
    OCCUPATION VARCHAR2(100),
    INCOME NUMBER(10,2),
    CONSTRAINT PK_FAMILY PRIMARY KEY (FAMILYID),
    CONSTRAINT FK_FAMILY_STUDENT
        FOREIGN KEY (STUDENTID)
        REFERENCES STUDENT(STUDENTID)
        ON DELETE CASCADE
);

-- =========================================================
-- STAFF
-- =========================================================
CREATE TABLE STAFF (
    STAFFID NUMBER GENERATED ALWAYS AS IDENTITY,
    STAFFNO VARCHAR2(50),
    PASSWORD VARCHAR2(255),
    NAME VARCHAR2(255),
    PHONENUM VARCHAR2(15),
    EMAIL VARCHAR2(255),
    CAMPUS VARCHAR2(255),
    CONSTRAINT PK_STAFF PRIMARY KEY (STAFFID)
);

-- =========================================================
-- DONATOR
-- =========================================================
CREATE TABLE DONATOR (
    DONATORID NUMBER GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR2(255),
    EMAIL VARCHAR2(255),
    PHONENUM VARCHAR2(15),
    CONSTRAINT PK_DONATOR PRIMARY KEY (DONATORID)
);

-- =========================================================
-- ZAKAT CATEGORY
-- =========================================================
CREATE TABLE ZAKAT_CATEGORY (
    ZAKATID NUMBER GENERATED ALWAYS AS IDENTITY,
    ZAKATNAME VARCHAR2(255),
    DESCRIPTION VARCHAR2(255),
    CONSTRAINT PK_ZAKAT_CATEGORY PRIMARY KEY (ZAKATID)
);

-- =========================================================
-- APPLICATION
-- =========================================================
CREATE TABLE APPLICATION (
    APPLYID NUMBER GENERATED ALWAYS AS IDENTITY,
    STUDENTID NUMBER,
    ZAKATID NUMBER,
    BANTUANMAKAN VARCHAR2(10),
    BANTUANKEWANGAN VARCHAR2(10),
    BANTUANKEWANGANNAMA VARCHAR2(255),
    BANTUANKEWANGANNILAI NUMBER(10,2),
    GRADYEAR NUMBER,
    CGPA NUMBER(10,2),
    GPA NUMBER(10,2),
    BANKNO VARCHAR2(50),
    BANKNAME VARCHAR2(255),
    STUDENTLETTER VARCHAR2(255),
    TRANSCRIPTDOC VARCHAR2(255),
    ICDOC VARCHAR2(255),
    STATUS VARCHAR2(20),
    REASON VARCHAR2(500),
    CONSTRAINT PK_APPLICATION PRIMARY KEY (APPLYID),
    CONSTRAINT FK_APP_STUDENT FOREIGN KEY (STUDENTID) REFERENCES STUDENT(STUDENTID),
    CONSTRAINT FK_APP_ZAKAT FOREIGN KEY (ZAKATID) REFERENCES ZAKAT_CATEGORY(ZAKATID)
);

-- =========================================================
-- DONATION
-- =========================================================
CREATE TABLE DONATION (
    DONATEID NUMBER GENERATED ALWAYS AS IDENTITY,
    BANKNAME VARCHAR2(50),
    AMOUNT NUMBER(10,2),
    DONATIONDATE DATE,
    NOTE VARCHAR2(50),
    DONATIONSTATUS VARCHAR2(50),
    STUDENTID NUMBER,
    DONATORID NUMBER,
    STAFFID NUMBER,
    CONSTRAINT PK_DONATION PRIMARY KEY (DONATEID),
    CONSTRAINT FK_DON_STUDENT FOREIGN KEY (STUDENTID) REFERENCES STUDENT(STUDENTID),
    CONSTRAINT FK_DON_DONATOR FOREIGN KEY (DONATORID) REFERENCES DONATOR(DONATORID),
    CONSTRAINT FK_DON_STAFF FOREIGN KEY (STAFFID) REFERENCES STAFF(STAFFID)
);

-- =========================================================
-- ZAKAT KOLEJ
-- =========================================================
CREATE TABLE ZAKAT_KOLEJ (
    KOLEJID NUMBER GENERATED ALWAYS AS IDENTITY,
    KOLEJNAME VARCHAR2(255),
    TOTALKOLEJ NUMBER(10,2),
    ZAKATID NUMBER,
    ELECTRONICAPPLIANCE VARCHAR2(255),
    KOLEJDOC VARCHAR2(255),
    CONSTRAINT PK_ZAKAT_KOLEJ PRIMARY KEY (KOLEJID),
    CONSTRAINT FK_KOLEJ_ZAKAT FOREIGN KEY (ZAKATID) REFERENCES ZAKAT_CATEGORY(ZAKATID)
);

-- =========================================================
-- ZAKAT MAKANAN
-- =========================================================
CREATE TABLE ZAKAT_MAKANAN (
    MAKANANID NUMBER GENERATED ALWAYS AS IDENTITY,
    CAFE VARCHAR2(50),
    ZAKATID NUMBER,
    CONSTRAINT PK_ZAKAT_MAKANAN PRIMARY KEY (MAKANANID),
    CONSTRAINT FK_MAKAN_ZAKAT FOREIGN KEY (ZAKATID) REFERENCES ZAKAT_CATEGORY(ZAKATID)
);

-- =========================================================
-- ZAKAT YURAN
-- =========================================================
CREATE TABLE ZAKAT_YURAN (
    YURANID NUMBER GENERATED ALWAYS AS IDENTITY,
    TOTALYURAN NUMBER(10,2),
    ZAKATID NUMBER,
    YURANDOC VARCHAR2(255),
    ENTRYSESSIONDOC VARCHAR2(255),
    CONSTRAINT PK_ZAKAT_YURAN PRIMARY KEY (YURANID),
    CONSTRAINT FK_YURAN_ZAKAT FOREIGN KEY (ZAKATID) REFERENCES ZAKAT_CATEGORY(ZAKATID)
);

-- =========================================================
-- WAITING
-- =========================================================
CREATE TABLE WAITING (
    APPLYID NUMBER,
    DATEWAIT DATE,
    REASON VARCHAR2(255),
    CONSTRAINT FK_WAIT_APP FOREIGN KEY (APPLYID) REFERENCES APPLICATION(APPLYID)
);

-- =========================================================
-- COMMENT
-- =========================================================
CREATE TABLE COMMENT (
    COMMENTID NUMBER GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255),
    COMMENTTEXT VARCHAR2(1000) NOT NULL,
    COMMENTDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_COMMENT PRIMARY KEY (COMMENTID)
);

COMMIT;




-- =====================================================
-- ORACLE XE 18c – DOCKER READY SCHEMA
-- Auto Increment using IDENTITY
-- NO sequences
-- NO triggers
-- =====================================================

-- =========================
-- ADMIN
-- =========================
CREATE TABLE ADMIN (
    ADMINID NUMBER GENERATED ALWAYS AS IDENTITY,
    USERNAME VARCHAR2(255),
    PASSWORD VARCHAR2(255),
    PHONENUM VARCHAR2(15),
    CONSTRAINT PK_ADMIN PRIMARY KEY (ADMINID)
);

-- =========================
-- STUDENT
-- =========================
CREATE TABLE STUDENT (
    STUDENTID NUMBER GENERATED ALWAYS AS IDENTITY,
    PASSWORD VARCHAR2(255),
    MATRICNO VARCHAR2(50),
    NAME VARCHAR2(255),
    INCOME NUMBER(10,2),
    COURSECODE VARCHAR2(50),
    COURSENAME VARCHAR2(255),
    CAMPUS VARCHAR2(255),
    EMAIL VARCHAR2(255),
    PHONENUM VARCHAR2(15),
    ADDRESS VARCHAR2(255),
    CONSTRAINT PK_STUDENT PRIMARY KEY (STUDENTID)
);

-- =========================
-- FAMILY (FIXED + VERIFIED)
-- =========================
CREATE TABLE FAMILY (
    FAMILYID NUMBER GENERATED ALWAYS AS IDENTITY,
    STUDENTID NUMBER NOT NULL,
    NAME VARCHAR2(255),
    RELATIONSHIP VARCHAR2(50),
    AGE NUMBER,
    OCCUPATION VARCHAR2(100),
    INCOME NUMBER(10,2),
    CONSTRAINT PK_FAMILY PRIMARY KEY (FAMILYID),
    CONSTRAINT FK_FAMILY_STUDENT
        FOREIGN KEY (STUDENTID)
        REFERENCES STUDENT(STUDENTID)
        ON DELETE CASCADE
);

-- =========================
-- STAFF
-- =========================
CREATE TABLE STAFF (
    STAFFID NUMBER GENERATED ALWAYS AS IDENTITY,
    STAFFNO VARCHAR2(50),
    PASSWORD VARCHAR2(255),
    NAME VARCHAR2(255),
    PHONENUM VARCHAR2(15),
    EMAIL VARCHAR2(255),
    CAMPUS VARCHAR2(255),
    CONSTRAINT PK_STAFF PRIMARY KEY (STAFFID)
);

-- =========================
-- DONATOR
-- =========================
CREATE TABLE DONATOR (
    DONATORID NUMBER GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR2(255),
    EMAIL VARCHAR2(255),
    PHONENUM VARCHAR2(15),
    CONSTRAINT PK_DONATOR PRIMARY KEY (DONATORID)
);

-- =========================
-- ZAKAT CATEGORY
-- =========================
CREATE TABLE ZAKAT_CATEGORY (
    ZAKATID NUMBER GENERATED ALWAYS AS IDENTITY,
    ZAKATNAME VARCHAR2(255),
    DESCRIPTION VARCHAR2(255),
    CONSTRAINT PK_ZAKAT_CATEGORY PRIMARY KEY (ZAKATID)
);

-- =========================
-- APPLICATION
-- =========================
CREATE TABLE APPLICATION (
    APPLYID NUMBER GENERATED ALWAYS AS IDENTITY,
    STUDENTID NUMBER NOT NULL,
    ZAKATID NUMBER NOT NULL,
    BANTUANMAKAN VARCHAR2(10),
    BANTUANKEWANGAN VARCHAR2(10),
    BANTUANKEWANGANNAMA VARCHAR2(255),
    BANTUANKEWANGANNILAI NUMBER(10,2),
    GRADYEAR NUMBER,
    CGPA NUMBER(10,2),
    GPA NUMBER(10,2),
    BANKNO VARCHAR2(50),
    BANKNAME VARCHAR2(255),
    STUDENTLETTER VARCHAR2(255),
    TRANSCRIPTDOC VARCHAR2(255),
    ICDOC VARCHAR2(255),
    STATUS VARCHAR2(20),
    REASON VARCHAR2(500),
    CONSTRAINT PK_APPLICATION PRIMARY KEY (APPLYID),
    CONSTRAINT FK_APP_STUDENT FOREIGN KEY (STUDENTID)
        REFERENCES STUDENT(STUDENTID),
    CONSTRAINT FK_APP_ZAKAT FOREIGN KEY (ZAKATID)
        REFERENCES ZAKAT_CATEGORY(ZAKATID)
);

-- =========================
-- DONATION
-- =========================
CREATE TABLE DONATION (
    DONATEID NUMBER GENERATED ALWAYS AS IDENTITY,
    BANKNAME VARCHAR2(50),
    AMOUNT NUMBER(10,2),
    DONATIONDATE DATE,
    NOTE VARCHAR2(50),
    DONATIONSTATUS VARCHAR2(50),
    STUDENTID NUMBER,
    DONATORID NUMBER,
    STAFFID NUMBER,
    CONSTRAINT PK_DONATION PRIMARY KEY (DONATEID),
    CONSTRAINT FK_DON_STUDENT FOREIGN KEY (STUDENTID)
        REFERENCES STUDENT(STUDENTID),
    CONSTRAINT FK_DON_DONATOR FOREIGN KEY (DONATORID)
        REFERENCES DONATOR(DONATORID),
    CONSTRAINT FK_DON_STAFF FOREIGN KEY (STAFFID)
        REFERENCES STAFF(STAFFID)
);

-- =========================
-- ZAKAT KOLEJ
-- =========================
CREATE TABLE ZAKAT_KOLEJ (
    KOLEJID NUMBER GENERATED ALWAYS AS IDENTITY,
    KOLEJNAME VARCHAR2(255),
    TOTALKOLEJ NUMBER(10,2),
    ZAKATID NUMBER,
    ELECTRONICAPPLIANCE VARCHAR2(255),
    KOLEJDOC VARCHAR2(255),
    CONSTRAINT PK_ZAKAT_KOLEJ PRIMARY KEY (KOLEJID),
    CONSTRAINT FK_KOLEJ_ZAKAT FOREIGN KEY (ZAKATID)
        REFERENCES ZAKAT_CATEGORY(ZAKATID)
);

-- =========================
-- ZAKAT MAKANAN
-- =========================
CREATE TABLE ZAKAT_MAKANAN (
    MAKANANID NUMBER GENERATED ALWAYS AS IDENTITY,
    CAFE VARCHAR2(50),
    ZAKATID NUMBER,
    CONSTRAINT PK_ZAKAT_MAKANAN PRIMARY KEY (MAKANANID),
    CONSTRAINT FK_MAKANAN_ZAKAT FOREIGN KEY (ZAKATID)
        REFERENCES ZAKAT_CATEGORY(ZAKATID)
);

-- =========================
-- ZAKAT YURAN
-- =========================
CREATE TABLE ZAKAT_YURAN (
    YURANID NUMBER GENERATED ALWAYS AS IDENTITY,
    TOTALYURAN NUMBER(10,2),
    ZAKATID NUMBER,
    YURANDOC VARCHAR2(255),
    ENTRYSESSIONDOC VARCHAR2(255),
    CONSTRAINT PK_ZAKAT_YURAN PRIMARY KEY (YURANID),
    CONSTRAINT FK_YURAN_ZAKAT FOREIGN KEY (ZAKATID)
        REFERENCES ZAKAT_CATEGORY(ZAKATID)
);

-- =========================
-- WAITING
-- =========================
CREATE TABLE WAITING (
    APPLYID NUMBER NOT NULL,
    DATEWAIT DATE,
    REASON VARCHAR2(255),
    CONSTRAINT FK_WAIT_APPLICATION FOREIGN KEY (APPLYID)
        REFERENCES APPLICATION(APPLYID)
);

-- =========================
-- COMMENT
-- =========================
CREATE TABLE COMMENT (
    COMMENTID NUMBER GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255),
    COMMENTTEXT VARCHAR2(1000) NOT NULL,
    COMMENTDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_COMMENT PRIMARY KEY (COMMENTID)
);

COMMIT;
